spring:
  application:
    name: authserver
  datasource:
    url: "jdbc:mysql://localhost:3308/authdb"
    username: authuser
    password: authpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 9000
