spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "book-service"
    description: "Library book-service application"
    version: "0.0.1"

server:
  port: 8081