DROP TABLE IF EXISTS books;

CREATE TABLE books (
                       id BIGINT AUTO_INCREMENT PRIMARY KEY,
                       title VARCHAR(50) NOT NULL,
                       author VARCHAR(50),
                       price DECIMAL(10,2),
                       stock INT
);

INSERT INTO books (title, author, price, stock) VALUES
                                                    ('El Quijote', 'Cervantes', 19.99, 10),
                                                    ('Cien Años de Soledad', 'García Márquez', 25.50, 5),
                                                    ('La Odisea', 'Homero', 15.75, 12),
                                                    ('La Iliada', 'Homero', 14.95, 7),
                                                    ('1984', 'George Orwell', 18.20, 9),
                                                    ('Rebelión en la Granja', 'George Orwell', 12.99, 14),
                                                    ('Fahrenheit 451', 'Ray Bradbury', 16.50, 8),
                                                    ('Crimen y Castigo', 'Dostoievski', 22.30, 6),
                                                    ('Los Hermanos Karamazov', 'Dostoievski', 24.99, 4),
                                                    ('Anna Karenina', 'Tolstoi', 21.80, 3),
                                                    ('Guerra y Paz', 'Tolstoi', 29.99, 2),
                                                    ('Orgullo y Prejuicio', 'Jane Austen', 17.45, 11),
                                                    ('Emma', 'Jane Austen', 16.75, 7),
                                                    ('Frankenstein', 'Mary Shelley', 14.30, 13),
                                                    ('Drácula', 'Bram Stoker', 15.60, 9),
                                                    ('El Principito', 'Antoine de Saint-Exupéry', 11.20, 25),
                                                    ('Don Juan Tenorio', 'José Zorrilla', 13.90, 5),
                                                    ('La Celestina', 'Fernando de Rojas', 12.50, 4),
                                                    ('La Divina Comedia', 'Dante Alighieri', 23.50, 6),
                                                    ('Hamlet', 'William Shakespeare', 18.40, 8),
                                                    ('Macbeth', 'William Shakespeare', 17.10, 10),
                                                    ('Romeo y Julieta', 'William Shakespeare', 16.80, 12),
                                                    ('Sueño de una Noche de Verano', 'William Shakespeare', 15.75, 6),
                                                    ('Moby Dick', 'Herman Melville', 20.50, 4),
                                                    ('La Cabaña del Tío Tom', 'Harriet Beecher Stowe', 14.95, 7),
                                                    ('Los Miserables', 'Victor Hugo', 26.30, 3),
                                                    ('Nuestra Señora de París', 'Victor Hugo', 21.70, 5),
                                                    ('Madame Bovary', 'Gustave Flaubert', 19.80, 6),
                                                    ('El Retrato de Dorian Gray', 'Oscar Wilde', 15.40, 9),
                                                    ('Ulises', 'James Joyce', 28.50, 2),
                                                    ('En Busca del Tiempo Perdido', 'Marcel Proust', 32.00, 1),
                                                    ('El Nombre de la Rosa', 'Umberto Eco', 22.10, 6),
                                                    ('El Padrino', 'Mario Puzo', 18.90, 10),
                                                    ('It', 'Stephen King', 25.40, 4),
                                                    ('El Resplandor', 'Stephen King', 23.00, 5),
                                                    ('Cementerio de Animales', 'Stephen King', 19.75, 6),
                                                    ('Carrie', 'Stephen King', 15.60, 8),
                                                    ('Apocalipsis', 'Stephen King', 27.50, 2),
                                                    ('Los Juegos del Hambre', 'Suzanne Collins', 18.40, 14),
                                                    ('En Llamas', 'Suzanne Collins', 19.10, 12),
                                                    ('Sinsajo', 'Suzanne Collins', 20.00, 11),
                                                    ('Harry Potter y la Piedra Filosofal', 'J.K. Rowling', 21.20, 20),
                                                    ('Harry Potter y la Cámara Secreta', 'J.K. Rowling', 22.10, 19),
                                                    ('Harry Potter y el Prisionero de Azkaban', 'J.K. Rowling', 23.40, 18),
                                                    ('Harry Potter y el Cáliz de Fuego', 'J.K. Rowling', 24.90, 17),
                                                    ('Harry Potter y la Orden del Fénix', 'J.K. Rowling', 26.20, 16),
                                                    ('Harry Potter y el Misterio del Príncipe', 'J.K. Rowling', 27.10, 15),
                                                    ('Harry Potter y las Reliquias de la Muerte', 'J.K. Rowling', 28.50, 14),
                                                    ('El Hobbit', 'J.R.R. Tolkien', 20.30, 13),
                                                    ('El Señor de los Anillos', 'J.R.R. Tolkien', 35.00, 10);
