spring:
  application:
    name: configserver

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sebasanguloc/Library_ms_config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

info:
  app:
    name: "order-service"
    description: "Library order-service application"
    version: "0.0.1"


server:
  port: 8071