spring:
  application:
    name: user-service
  config:
    import: "optional:${CONFIGSERVER_IMPORT}"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "user-service"
    description: "Library user-service application"
    version: "0.0.1"

server:
  port: 8082

