spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "user-service"
    description: "Library user-service application"
    version: "0.0.1"

server:
  port: 8082

