spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
